# Generated by Django 2.2.2 on 2019-07-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='QA.Tag'),
        ),
    ]
