# Generated by Django 2.2.3 on 2019-07-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='bio',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
