# Generated by Django 2.2.2 on 2019-07-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='premium',
            field=models.BooleanField(default=False),
        ),
    ]
