# Generated by Django 2.2.2 on 2019-06-09 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_info', to='store.Chapter')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_chapters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('chapter', 'member')},
            },
        ),
    ]
