# Generated by Django 2.2.2 on 2019-06-13 08:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_purchasehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasehistory',
            name='bought_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
